"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import { Layout } from "antd";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    const { Header, Content, Footer } = Layout;
    return (
        <html lang="en">
            <body className={inter.className}>
                <Layout className="layout">
                    <Header className="flex items-center justify-center">
                        <span className="text-white text-2xl font-bold italic tracking-tighter">
                            💸 AuditDana
                        </span>
                    </Header>
                    <Content className="min-h-screen bg-gradient-to-b from-c-blue-100 to-neutral-100">
                        <div className="site-layout-content">{children}</div>
                    </Content>
                    <Footer className="bg-c-blue-500 text-center text-white">
                        AuditDana © 2023
                    </Footer>
                </Layout>
            </body>
        </html>
    );
}
